#!/usr/bin/env bash

# shellcheck disable=SC1091

if [[ $1 == "install" ]]
then
    rm models.db
    pip install --user -r dependencies.txt && poetry install
elif [[ $1 == "test" ]]
then
    python test_runner.py
else
    python src/__main__.py analyze "$1"
fi