#!/usr/bin/env bash
python3 -m venv venv
# shellcheck disable=SC1091
source venv/bin/activate

if [[ $1 == "install" ]]
then
    pip install -r dependencies.txt
    poetry install
elif [[ $1 == "test" ]]
then
    python src/__main__.py test
else
    python src/__main__.py analyze "$1"
fi