My Project: src.database.SQLiteAccessor Class Reference
src.database.SQLiteAccessor Class Reference
Public Member Functions
__init__ (self, db_location, list metric_schema, bool create_if_missing=True)
__del__ (self)
bool db_exists (self)
init_database (self)
get_database_metrics_if_exists (self, str url, list schema)
bool check_entry_in_db (self, str url)
add_to_db (self, ModelStats model_stats)
ModelStats get_model_statistics (self, str model_url)
Public Attributes
sqlite3.Connection connection = sqlite3.connect(":memory:")
sqlite3.Cursor cursor = self.connection.cursor()
metric_schema = metric_schema
Constructor & Destructor Documentation
__init__()
src.database.SQLiteAccessor.__init__ (self, db_location, list metric_schema, bool create_if_missing = True)
__del__()
src.database.SQLiteAccessor.__del__ (self)
References connection.
Member Function Documentation
add_to_db()
src.database.SQLiteAccessor.add_to_db (self, ModelStats model_stats)
References connection, and cursor.
check_entry_in_db()
bool src.database.SQLiteAccessor.check_entry_in_db (self, str url)
References cursor.
db_exists()
bool src.database.SQLiteAccessor.db_exists (self)
References cursor, and metric_schema.
get_database_metrics_if_exists()
src.database.SQLiteAccessor.get_database_metrics_if_exists (self, str url, list schema)
References cursor.
get_model_statistics()
ModelStats src.database.SQLiteAccessor.get_model_statistics (self, str model_url)
References cursor, and metric_schema.
init_database()
src.database.SQLiteAccessor.init_database (self)
References connection, cursor, and metric_schema.
Member Data Documentation
connection
sqlite3.Connection src.database.SQLiteAccessor.connection = sqlite3.connect(":memory:")
Referenced by __del__(), add_to_db(), and init_database().
cursor
sqlite3.Cursor src.database.SQLiteAccessor.cursor = self.connection.cursor()
Referenced by add_to_db(), check_entry_in_db(), db_exists(), get_database_metrics_if_exists(), get_model_statistics(), and init_database().
metric_schema
src.database.SQLiteAccessor.metric_schema = metric_schema
Referenced by db_exists(), get_model_statistics(), and init_database().
The documentation for this class was generated from the following file:
src/database.py