My Project: src.metrics.size_metric.SizeMetric Class Reference
src.metrics.size_metric.SizeMetric Class Reference
Metric that evaluates model size against target device capabilities.
Public Member Functions
__init__ (self)
Initialize the SizeMetric with default values.
setup_resources (self)
Set up resources by fetching model information from HuggingFace API.
calculate_device_score (self, dict device_spec)
dict[str, float] calculate_score (self)
Calculate the size metric score based on storage and memory constraints.
dict get_size_details (self, device_name)
Get detailed size information for debugging and analysis.
Public Member Functions inherited from src.metric.BaseMetric
__init__ (self)
Initializes the BaseMetric with default values.
Self run (self)
Sets up resources and calculates the metric score.
Self set_params (self, int priority, str platform)
Sets the priority and target platform for the metric.
set_url (self, ModelURLs url)
Sets the URL for the metric.
set_local_directory (self, ModelPaths local_directory)
Public Attributes
dict model_info = None
int storage_size_mb = 0
int memory_size_mb = 0
dict param_source = None
Public Attributes inherited from src.metric.BaseMetric
float score = 0.0
url = None
int priority = 1
typing.Optional[str] target_platform = None
local_directory = None
float runtime = 0.0
Static Public Attributes
str metric_name = "size_score"
Protected Member Functions
dict _fetch_model_info (self)
Fetch model information from HuggingFace API.
str _extract_repo_id_from_url (self)
Extract repository ID from HuggingFace URL.
dict _get_fallback_model_info (self)
Provide fallback model information when API is unavailable.
float _calculate_storage_size (self)
Calculate storage size requirements in MB.
float _calculate_memory_size (self)
Calculate memory requirements in MB for loading the model.
int _get_parameter_count (self)
Extract or estimate the number of parameters in the model.
int _estimate_parameters_from_config (self, dict cfg)
Estimate parameter count from model configuration.
str _get_tensor_type (self)
Determine the tensor type used by the model.
Detailed Description
Metric that evaluates model size against target device capabilities.
Calculates storage and memory requirements, assigns score based on:
Storage fit (0 if doesn't fit, continue if fits)
Memory usage and remaining free memory
Constructor & Destructor Documentation
__init__()
src.metrics.size_metric.SizeMetric.__init__ (self)
Initialize the SizeMetric with default values.
References __init__().
Referenced by __init__().
Member Function Documentation
_calculate_memory_size()
float src.metrics.size_metric.SizeMetric._calculate_memory_size (self) protected
Calculate memory requirements in MB for loading the model.
Returns
float Memory size in megabytes.
References _get_parameter_count(), _get_tensor_type(), and model_info.
Referenced by setup_resources().
_calculate_storage_size()
float src.metrics.size_metric.SizeMetric._calculate_storage_size (self) protected
Calculate storage size requirements in MB.
Returns
float Storage size in megabytes.
References _get_parameter_count(), _get_tensor_type(), and model_info.
Referenced by setup_resources().
_estimate_parameters_from_config()
int src.metrics.size_metric.SizeMetric._estimate_parameters_from_config (self, dict cfg) protected
Estimate parameter count from model configuration.
Estimate based on common model architchtures (Transformer-based).
Parameters
config Model configuration.
Returns
int Estimated parameter count.
References src.metrics.size_metric._get_cfg().
Referenced by _get_parameter_count().
_extract_repo_id_from_url()
str src.metrics.size_metric.SizeMetric._extract_repo_id_from_url (self) protected
Extract repository ID from HuggingFace URL.
Returns
str Repository ID
Referenced by _fetch_model_info().
_fetch_model_info()
dict src.metrics.size_metric.SizeMetric._fetch_model_info (self) protected
Fetch model information from HuggingFace API.
Returns
dict Model information including config and file details.
Exceptions
requests If API request fails.
References _extract_repo_id_from_url(), and _get_fallback_model_info().
Referenced by setup_resources().
_get_fallback_model_info()
dict src.metrics.size_metric.SizeMetric._get_fallback_model_info (self) protected
Provide fallback model information when API is unavailable.
Returns
dict Conservative estimates for model parameters.
Referenced by _fetch_model_info().
_get_parameter_count()
int src.metrics.size_metric.SizeMetric._get_parameter_count (self) protected
Extract or estimate the number of parameters in the model.
Returns
int Number of parameters.
References _estimate_parameters_from_config(), and model_info.
Referenced by _calculate_memory_size(), _calculate_storage_size(), and get_size_details().
_get_tensor_type()
str src.metrics.size_metric.SizeMetric._get_tensor_type (self) protected
Determine the tensor type used by the model.
Returns
str Tensor type (e.g., 'float32', 'float16').
References model_info.
Referenced by _calculate_memory_size(), _calculate_storage_size(), and get_size_details().
calculate_device_score()
src.metrics.size_metric.SizeMetric.calculate_device_score (self, dict device_spec)
References memory_size_mb, param_source, and storage_size_mb.
Referenced by calculate_score().
calculate_score()
dict[str, float] src.metrics.size_metric.SizeMetric.calculate_score (self)
Calculate the size metric score based on storage and memory constraints.
Returns
dict[str, float]: Score for each device between 0.0 and 1.0 where:
0.0: Model doesn't fit on storage
0.1-1.0: Model fits, score based on remaining memory percentage
Reimplemented from src.metric.BaseMetric.
References calculate_device_score().
get_size_details()
dict src.metrics.size_metric.SizeMetric.get_size_details (self, device_name)
Get detailed size information for debugging and analysis.
Parameters
device_name name of the device to get details of
Returns
dict Detailed size breakdown.
References _get_parameter_count(), _get_tensor_type(), memory_size_mb, and storage_size_mb.
setup_resources()
src.metrics.size_metric.SizeMetric.setup_resources (self)
Set up resources by fetching model information from HuggingFace API.
Exceptions
IOError If model information cannot be retrieved.
Reimplemented from src.metric.BaseMetric.
References _calculate_memory_size(), _calculate_storage_size(), _fetch_model_info(), memory_size_mb, model_info, param_source, and storage_size_mb.
Member Data Documentation
memory_size_mb
src.metrics.size_metric.SizeMetric.memory_size_mb = 0
Referenced by calculate_device_score(), get_size_details(), and setup_resources().
metric_name
str src.metrics.size_metric.SizeMetric.metric_name = "size_score" static
model_info
dict src.metrics.size_metric.SizeMetric.model_info = None
Referenced by _calculate_memory_size(), _calculate_storage_size(), _get_parameter_count(), _get_tensor_type(), and setup_resources().
param_source
dict src.metrics.size_metric.SizeMetric.param_source = None
Referenced by calculate_device_score(), and setup_resources().
storage_size_mb
src.metrics.size_metric.SizeMetric.storage_size_mb = 0
Referenced by calculate_device_score(), get_size_details(), and setup_resources().
The documentation for this class was generated from the following file:
src/metrics/size_metric.py