My Project: src.metrics.ramp_up_time.RampUpMetric Class Reference
src.metrics.ramp_up_time.RampUpMetric Class Reference
Public Member Functions
__init__ (self, float half_score_time_minutes, Literal["cpu", "mps", "cuda", "cuda:0"] device_type)
setup_resources (self)
Abstract method to set up necessary resources for the metric.
installation_spin_up_score (self)
float calculate_score (self)
Abstract method to calculate the metric score.
Public Member Functions inherited from src.metric.BaseMetric
__init__ (self)
Initializes the BaseMetric with default values.
Self run (self)
Sets up resources and calculates the metric score.
Self set_params (self, int priority, str platform)
Sets the priority and target platform for the metric.
set_url (self, ModelURLs url)
Sets the URL for the metric.
set_local_directory (self, ModelPaths local_directory)
Public Attributes
Literal[,,,] device_type = device_type
float exponential_coefficient = -log(0.5) / half_score_time_minutes
Public Attributes inherited from src.metric.BaseMetric
float score = 0.0
url = None
int priority = 1
typing.Optional[str] target_platform = None
local_directory = None
float runtime = 0.0
Static Public Attributes
str metric_name = "ramp_up_time"
Constructor & Destructor Documentation
__init__()
src.metrics.ramp_up_time.RampUpMetric.__init__ (self, float half_score_time_minutes, Literal["cpu", "mps", "cuda", "cuda:0"] device_type)
References __init__().
Referenced by __init__().
Member Function Documentation
calculate_score()
float src.metrics.ramp_up_time.RampUpMetric.calculate_score (self)
Abstract method to calculate the metric score.
Should be implemented by subclasses.
Returns
float The calculated score.
Reimplemented from src.metric.BaseMetric.
References installation_spin_up_score().
installation_spin_up_score()
src.metrics.ramp_up_time.RampUpMetric.installation_spin_up_score (self)
Referenced by calculate_score().
setup_resources()
src.metrics.ramp_up_time.RampUpMetric.setup_resources (self)
Abstract method to set up necessary resources for the metric.
Should be implemented by subclasses.
Reimplemented from src.metric.BaseMetric.
Member Data Documentation
device_type
Literal[, , , ] src.metrics.ramp_up_time.RampUpMetric.device_type = device_type
exponential_coefficient
float src.metrics.ramp_up_time.RampUpMetric.exponential_coefficient = -log(0.5) / half_score_time_minutes
metric_name
str src.metrics.ramp_up_time.RampUpMetric.metric_name = "ramp_up_time" static
The documentation for this class was generated from the following file:
src/metrics/ramp_up_time.py