My Project: src.download_manager.DownloadManager Class Reference
src.download_manager.DownloadManager Class Reference
Manages downloading and caching of models, datasets, and codebases.
Public Member Functions
__init__ (self, str models_dir="models", str codebases_dir="codebases", str datasets_dir="datasets")
Path download_model (self, str model_url)
Download or update a HuggingFace model to local storage.
Path download_dataset (self, str dataset_url)
Download or update a HuggingFace dataset to local storage.
Path download_codebase (self, str code_url)
Download or update a git repository to local storage.
Optional[Path] check_local_model (self, str model_url)
Optional[Path] check_local_dataset (self, str dataset_url)
Optional[Path] check_local_codebase (self, str code_url)
Tuple[Optional[Path], Optional[Path], Optional[Path]] download_model_resources (self, ModelURLs model_urls, bool download_model=True, bool download_codebase=True, bool download_dataset=True)
Public Attributes
models_dir = Path(models_dir)
codebases_dir = Path(codebases_dir)
datasets_dir = Path(datasets_dir)
Protected Member Functions
str _extract_repo_id (self, str url)
Extract repository ID from HuggingFace URL.
str _extract_repo_name (self, str code_url)
Extract repository name from git URL.
Detailed Description
Manages downloading and caching of models, datasets, and codebases.
Always updates existing resources when downloading.
Constructor & Destructor Documentation
__init__()
src.download_manager.DownloadManager.__init__ (self, str models_dir = "models", str codebases_dir = "codebases", str datasets_dir = "datasets")
Parameters
models_dir Directory to store downloaded models
codebases_dir Directory to store downloaded codebases
datasets_dir Directory to store downloaded datasets
Member Function Documentation
_extract_repo_id()
str src.download_manager.DownloadManager._extract_repo_id (self, str url) protected
Extract repository ID from HuggingFace URL.
Parameters
url HuggingFace model/dataset URL
Returns
Repository ID (e.g., "username/model-name")
Referenced by check_local_dataset(), check_local_model(), download_dataset(), and download_model().
_extract_repo_name()
str src.download_manager.DownloadManager._extract_repo_name (self, str code_url) protected
Extract repository name from git URL.
Parameters
code_url Git repository URL
Returns
Repository name
Referenced by check_local_codebase(), and download_codebase().
check_local_codebase()
Optional[Path] src.download_manager.DownloadManager.check_local_codebase (self, str code_url)
Parameters
code_url Git repository URL
Returns
Path to codebase if exists, None otherwise
References _extract_repo_name(), and codebases_dir.
check_local_dataset()
Optional[Path] src.download_manager.DownloadManager.check_local_dataset (self, str dataset_url)
Parameters
dataset_url HuggingFace dataset URL
Returns
Path to dataset if exists, None otherwise
References _extract_repo_id(), and datasets_dir.
check_local_model()
Optional[Path] src.download_manager.DownloadManager.check_local_model (self, str model_url)
Parameters
model_url HuggingFace model URL
Returns
Path to model if exists, None otherwise
References _extract_repo_id(), and models_dir.
download_codebase()
Path src.download_manager.DownloadManager.download_codebase (self, str code_url)
Download or update a git repository to local storage.
Always pulls latest changes if repository exists.
Parameters
code_url Git repository URL
Returns
Path to the downloaded codebase directory
References _extract_repo_name(), and codebases_dir.
Referenced by download_model_resources().
download_dataset()
Path src.download_manager.DownloadManager.download_dataset (self, str dataset_url)
Download or update a HuggingFace dataset to local storage.
Always updates if dataset exists locally.
Parameters
dataset_url HuggingFace dataset URL
Returns
Path to the downloaded dataset directory
References _extract_repo_id(), and datasets_dir.
Referenced by download_model_resources().
download_model()
Path src.download_manager.DownloadManager.download_model (self, str model_url)
Download or update a HuggingFace model to local storage.
Always updates if model exists locally.
Parameters
model_url HuggingFace model URL
Returns
Path to the downloaded model directory
References _extract_repo_id(), and models_dir.
Referenced by download_model_resources().
download_model_resources()
Tuple[Optional[Path], Optional[Path], Optional[Path]] src.download_manager.DownloadManager.download_model_resources (self, ModelURLs model_urls, bool download_model = True, bool download_codebase = True, bool download_dataset = True)
Parameters
model_urls ModelURLs object containing URLs
download_model Whether to download the model
download_codebase Whether to download the codebase
download_dataset Whether to download the dataset
Returns
Tuple of (model_path, codebase_path, dataset_path)
References download_codebase(), download_dataset(), and download_model().
Member Data Documentation
codebases_dir
src.download_manager.DownloadManager.codebases_dir = Path(codebases_dir)
Referenced by check_local_codebase(), and download_codebase().
datasets_dir
src.download_manager.DownloadManager.datasets_dir = Path(datasets_dir)
Referenced by check_local_dataset(), and download_dataset().
models_dir
src.download_manager.DownloadManager.models_dir = Path(models_dir)
Referenced by check_local_model(), and download_model().
The documentation for this class was generated from the following file:
src/download_manager.py