My Project: src.metrics.dataset_quality.DatasetQualityMetric Class Reference
src.metrics.dataset_quality.DatasetQualityMetric Class Reference
Public Member Functions
__init__ (self)
float scale_logarithmically (self, float value, float zero, float one)
setup_resources (self)
Abstract method to set up necessary resources for the metric.
float calculate_score (self)
Abstract method to calculate the metric score.
Public Member Functions inherited from src.metric.BaseMetric
__init__ (self)
Initializes the BaseMetric with default values.
Self run (self)
Sets up resources and calculates the metric score.
Self set_params (self, int priority, str platform)
Sets the priority and target platform for the metric.
set_url (self, ModelURLs url)
Sets the URL for the metric.
set_local_directory (self, ModelPaths local_directory)
Static Public Attributes
str metric_name = "dataset_quality"
Additional Inherited Members
Public Attributes inherited from src.metric.BaseMetric
float score = 0.0
url = None
int priority = 1
typing.Optional[str] target_platform = None
local_directory = None
float runtime = 0.0
Constructor & Destructor Documentation
__init__()
src.metrics.dataset_quality.DatasetQualityMetric.__init__ (self)
References __init__().
Referenced by __init__().
Member Function Documentation
calculate_score()
float src.metrics.dataset_quality.DatasetQualityMetric.calculate_score (self)
Abstract method to calculate the metric score.
Should be implemented by subclasses.
Returns
float The calculated score.
Reimplemented from src.metric.BaseMetric.
References scale_logarithmically(), and src.metric.BaseMetric.url.
scale_logarithmically()
float src.metrics.dataset_quality.DatasetQualityMetric.scale_logarithmically (self, float value, float zero, float one)
Referenced by calculate_score().
setup_resources()
src.metrics.dataset_quality.DatasetQualityMetric.setup_resources (self)
Abstract method to set up necessary resources for the metric.
Should be implemented by subclasses.
Reimplemented from src.metric.BaseMetric.
Member Data Documentation
metric_name
str src.metrics.dataset_quality.DatasetQualityMetric.metric_name = "dataset_quality" static
The documentation for this class was generated from the following file:
src/metrics/dataset_quality.py