My Project: src.metrics.bus_factor.BusFactorMetric Class Reference
src.metrics.bus_factor.BusFactorMetric Class Reference
Public Member Functions
__init__ (self)
tuple[int, dict[str, int]] parse_response (self)
float calculate_bus_factor (self, int total_commits, dict[str, int] commit_score)
float calc_weighted_sum (self, int codebase_commits, int model_commits, float codebase_factor, float model_factor)
tuple[int, dict[str, int]] parse_model (self)
float calculate_score (self)
Abstract method to calculate the metric score.
setup_resources (self)
Abstract method to set up necessary resources for the metric.
Public Member Functions inherited from src.metric.BaseMetric
__init__ (self)
Initializes the BaseMetric with default values.
Self run (self)
Sets up resources and calculates the metric score.
Self set_params (self, int priority, str platform)
Sets the priority and target platform for the metric.
set_url (self, ModelURLs url)
Sets the URL for the metric.
set_local_directory (self, ModelPaths local_directory)
Public Attributes
response = None
Public Attributes inherited from src.metric.BaseMetric
float score = 0.0
url = None
int priority = 1
typing.Optional[str] target_platform = None
local_directory = None
float runtime = 0.0
Static Public Attributes
str metric_name = "bus_factor"
str graphql_query
Constructor & Destructor Documentation
__init__()
src.metrics.bus_factor.BusFactorMetric.__init__ (self)
Member Function Documentation
calc_weighted_sum()
float src.metrics.bus_factor.BusFactorMetric.calc_weighted_sum (self, int codebase_commits, int model_commits, float codebase_factor, float model_factor)
Referenced by calculate_score().
calculate_bus_factor()
float src.metrics.bus_factor.BusFactorMetric.calculate_bus_factor (self, int total_commits, dict[str, int] commit_score)
Referenced by calculate_score().
calculate_score()
float src.metrics.bus_factor.BusFactorMetric.calculate_score (self)
Abstract method to calculate the metric score.
Should be implemented by subclasses.
Returns
float The calculated score.
Reimplemented from src.metric.BaseMetric.
References calc_weighted_sum(), calculate_bus_factor(), parse_model(), and parse_response().
parse_model()
tuple[int, dict[str, int]] src.metrics.bus_factor.BusFactorMetric.parse_model (self)
References src.metric.BaseMetric.url.
Referenced by calculate_score().
parse_response()
tuple[int, dict[str, int]] src.metrics.bus_factor.BusFactorMetric.parse_response (self)
References response.
Referenced by calculate_score().
setup_resources()
src.metrics.bus_factor.BusFactorMetric.setup_resources (self)
Abstract method to set up necessary resources for the metric.
Should be implemented by subclasses.
Reimplemented from src.metric.BaseMetric.
References graphql_query, response, setup_resources(), and src.metric.BaseMetric.url.
Referenced by setup_resources().
Member Data Documentation
graphql_query
str src.metrics.bus_factor.BusFactorMetric.graphql_query static
Initial value:
=  """
{
repository(name:"%s", owner:"%s"){
    refs(refPrefix:"refs/heads/", first:30){
      edges{
        node{
          target{
        ...on Commit{
          history(first:30, since:"2020-01-01T00:00:00.000Z") {
            edges {
              node {
                author{
                  email
                }
              }
            }
          }
        }
      }
        }
      }
    }
  }
  }"""
Referenced by setup_resources().
metric_name
str src.metrics.bus_factor.BusFactorMetric.metric_name = "bus_factor" static
response
src.metrics.bus_factor.BusFactorMetric.response = None
Referenced by parse_response(), and setup_resources().
The documentation for this class was generated from the following file:
src/metrics/bus_factor.py