My Project: src.config Namespace Reference
src.config Namespace Reference
Classes
class ConfigContract
class ModelPaths
class ModelURLs
Stores URLs related to a model, including model, codebase, and dataset URLs.
class PFExponentialDecay
Priority function using exponential decay.
class PFReciprocal
Priority function using reciprocal weighting.
class PriorityFunction
Abstract base class for priority weighting functions.
Functions
str extract_model_repo_id (str model_url)
str extract_dataset_repo_id (str dataset_url)
str extract_code_repo_name (str code_url)
ModelPaths generate_model_paths (ConfigContract contract, ModelURLs urls)
Variables
str DATASET = "dataset"
str CODEBASE = "codebase"
str MODEL = "model"
Function Documentation
extract_code_repo_name()
str src.config.extract_code_repo_name (str code_url)
Parameters
code_url Git repository URL
Returns
Repository name
Referenced by generate_model_paths().
extract_dataset_repo_id()
str src.config.extract_dataset_repo_id (str dataset_url)
Parameters
dataset_url HuggingFace dataset URL
Returns
Dataset repository ID (e.g., "username/dataset-name")
Referenced by generate_model_paths().
extract_model_repo_id()
str src.config.extract_model_repo_id (str model_url)
Parameters
model_url HuggingFace model URL
Returns
Repository ID (e.g., "username/model-name")
Referenced by src.__main__.calculate_metrics(), and generate_model_paths().
generate_model_paths()
ModelPaths src.config.generate_model_paths (ConfigContract contract, ModelURLs urls)
References extract_code_repo_name(), extract_dataset_repo_id(), and extract_model_repo_id().
Referenced by src.__main__.analyze(), and src.__main__.calculate_metrics().
Variable Documentation
CODEBASE
str src.config.CODEBASE = "codebase"
DATASET
str src.config.DATASET = "dataset"
MODEL
str src.config.MODEL = "model"