My Project: src.__main__ Namespace Reference
src.__main__ Namespace Reference
Functions
setup_logging ()
Setup logging based on environment variables.
List[ModelURLs] parse_url_file (Path url_file)
Parses a file containing comma-separated URLs and returns ModelURLs objects.
stage_metrics (ConfigContract config)
ModelStats calculate_metrics (ModelURLs model_urls, ConfigContract config, MetricStager stager)
Calculate all metrics for a given model.
install ()
Installs necessary dependencies from dependencies.txt.
test ()
analyze (Path url_file)
Analyzes models based on URLs provided in a file.
Variables
app = typer.Typer()
Function Documentation
analyze()
src.__main__.analyze (Path url_file)
Analyzes models based on URLs provided in a file.
Will add model to database if not already present.
References app, calculate_metrics(), src.config.generate_model_paths(), parse_url_file(), setup_logging(), and stage_metrics().
calculate_metrics()
ModelStats src.__main__.calculate_metrics (ModelURLs model_urls, ConfigContract config, MetricStager stager)
Calculate all metrics for a given model.
References src.config.extract_model_repo_id(), and src.config.generate_model_paths().
Referenced by analyze().
install()
src.__main__.install ()
Installs necessary dependencies from dependencies.txt.
parse_url_file()
List[ModelURLs] src.__main__.parse_url_file (Path url_file)
Parses a file containing comma-separated URLs and returns ModelURLs objects.
Format code_link, dataset_link, model_link (per line)
Referenced by analyze().
setup_logging()
src.__main__.setup_logging ()
Setup logging based on environment variables.
Referenced by analyze(), and test().
stage_metrics()
src.__main__.stage_metrics (ConfigContract config)
Referenced by analyze().
test()
src.__main__.test ()
References setup_logging().
Variable Documentation
app
src.__main__.app = typer.Typer()
Referenced by analyze().